# local deste arquivo: ./docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend_network
    restart: always

  backend:
    build: ./backend
    env_file:
      - ./.env
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend_network
    restart: always


  frontend:
    build: ./frontend
    env_file:
      - ./.env
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - frontend_network
      - backend_network
    restart: always


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./.env
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - backend_network
    restart: always


volumes:
  mysql_data:
    external: true

networks:
  frontend_network:
  backend_network: