## após a incialização do samba entre no container e execute o scrpit

# docker exec -it samba bash

# chmod +x /etc/samba/configura_usuario_samba.sh && sh /etc/samba/configura_usuario_samba.sh

## Saia e reinicie o container

# docker restart samba
version: '3.8'

services:

  samba:
    image: dperson/samba
    container_name: samba
    env_file:
      - /home/boxuser/sge/samba_servidor/.env
    environment:
      - SMB_USER=${SMB_USER}
      - SMB_PASS=${SMB_PASS}
    volumes:
      - /minhaect:/minhaect
      - ./configura_usuario_samba.sh:/etc/samba/configura_usuario_samba.sh
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    restart: always